# Generated by Django 5.0.2 on 2024-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_section_product_additional_information_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
    ]
