# Generated by Django 5.0.2 on 2024-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_information',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Categories',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Additional_Information',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
    ]
